version: 2

seeds:
  - name: AMENITIES_CHANGELOG
    description: Historical changes to listing amenities
    config:
      column_types:
        LISTING_ID: integer
        CHANGE_AT: datetime
        AMENITIES: varchar
    columns:
      - name: LISTING_ID
        description: Unique ID for the listing to which this row applies. Part of the Primary Key.
        tests:
          - not_null
      - name: CHANGE_AT
        description: When the amenities list changed.
        tests:
          - not_null
      - name: AMENITIES
        description: Array of the amenities available as of the change. Parseable as JSON.

  - name: CALENDAR
    description: Listing availability calendar data
    config:
      column_types:
        LISTING_ID: integer
        # Official docs say this is datetime, but all values are actually dates, so ingesting as date.
        DATE: date
        AVAILABLE: varchar
        RESERVATION_ID: varchar
        PRICE: varchar
        MINIMUM_NIGHTS: integer
        MAXIMUM_NIGHTS: integer
    columns:
      - name: LISTING_ID
        description: Unique ID for the listing to which this row applies. Part of the Primary Key.
        tests:
          - not_null
      - name: DATE
        description: Date of availability this row describes. Part of the Primary Key.
        tests:
          - not_null
      - name: AVAILABLE
        description: Contains 't' if this property is available on this date. Contains 'f' if not.
      - name: RESERVATION_ID
        description: Unique ID for that DATE's reservation. Foreign key. If NULL, there was no reservation on that date.
      - name: PRICE
        description: The USD price to rent this property on DATE.
      - name: MINIMUM_NIGHTS
        description: The minimum number of nights that must be booked consecutively for this property.
      - name: MAXIMUM_NIGHTS
        description: The maximum number of nights that may be booked consecutively for this property.

  - name: LISTINGS
    description: Airbnb listing data
    config:
      column_types:
        ID: integer
        NAME: varchar
        HOST_ID: integer
        HOST_NAME: varchar
        HOST_SINCE: datetime
        HOST_LOCATION: varchar
        HOST_VERIFICATIONS: varchar
        NEIGHBORHOOD: varchar
        PROPERTY_TYPE: varchar
        ROOM_TYPE: varchar
        ACCOMMODATES: integer
        BATHROOMS_TEXT: varchar
        BEDROOMS: varchar
        BEDS: integer
        AMENITIES: varchar
        PRICE: varchar
        NUMBER_OF_REVIEWS: integer
        FIRST_REVIEW: varchar
        LAST_REVIEW: varchar
        REVIEW_SCORES_RATING: varchar
    columns:
      - name: ID
        description: Unique ID for this listing. Primary Key.
        tests:
          - unique
          - not_null
      - name: NAME
        description: Display name of listing.
      - name: HOST_ID
        description: Unique ID for the Host who owns this property.
        tests:
          - not_null
      - name: HOST_NAME
        description: Display name of Host.
      - name: HOST_SINCE
        description: When the Host signed up.
      - name: HOST_LOCATION
        description: Where the Host is based.
      - name: HOST_VERIFICATIONS
        description: Array of methods the Host can use to verify. Parseable as JSON.
      - name: NEIGHBORHOOD
        description: The neighborhood where this listing is located.
      - name: PROPERTY_TYPE
        description: Description of the type of property.
      - name: ROOM_TYPE
        description: Description of the type of room.
      - name: ACCOMMODATES
        description: Number of guests this room can accommodate.
      - name: BATHROOMS_TEXT
        description: Number and types of bathrooms available.
      - name: BEDROOMS
        description: Number of bedrooms available for use.
      - name: BEDS
        description: Number of beds available for use.
      - name: AMENITIES
        description: Array of amenities available for guests. Parseable as JSON.
      - name: PRICE
        description: The price of this listing as of the start of the date range in CALENDAR.
      - name: NUMBER_OF_REVIEWS
        description: The number of reviews this listing has ever received.
      - name: FIRST_REVIEW
        description: The date of the first review this listing received.
      - name: LAST_REVIEW
        description: The date of the most recent review this listing received.
      - name: REVIEW_SCORES_RATING
        description: The average review score of this listing.
