version: 2

seeds:
  - name: customers
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: email
        tests:
          - not_null
          - unique

models:
  - name: stg_customers
    description: "Staging customers from seeds"
    columns:
      - name: customer_id
        tests:
          - not_null

  - name: core_customers
    description: "Final customer mart"
